#!/bin/sh

export OCCI_ENDPOINT=http://server4-eupt.unizar.es:8787/
export OS_TPL=http://schemas.openstack.org/template/os#584a0134-59dd-4d71-8e50-315ab802fe7f
export RESOURCE_TPL=http://schemas.openstack.org/template/resource#m1-tiny
export PUBLIC_KEY="file://$HOME/w/cloud/creds/enolkey-pub.pem"

set -x
VM=`occi -e $OCCI_ENDPOINT \
     -n x509 -X -x $X509_USER_PROXY \
     -a create -r compute  \
     -M $OS_TPL -M $RESOURCE_TPL \
     -t occi.core.title="MyTutorialContextVM_$(date +%s)" \
     -T user_data="file://$PWD/user_data" \
     -T public_key="$PUBLIC_KEY" || echo "ERROR"`
set +x
echo $VM
